---
# Update system Install Docker 
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600
  
- name: Upgrade all apt packages
  apt: upgrade=dist
  
- name: Install dependencies
  apt:
   name: "{{ packages }}"
   state: present
   update_cache: yes
  vars:
   packages:
   - apt-transport-https
   - ca-certificates
   - curl
   - software-properties-common
   - net-tools

- name: Add an apt signing key for Docker
  apt_key:
   url: https://download.docker.com/linux/ubuntu/gpg

- name: Add The Docker Repository
  apt_repository:
   repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
   state: present  

- name: Install Docker
  apt:
   name: docker-ce
   state: present

- name: Docker service Start
  service:
   name: docker
   state: started

- name: Allow vagrant user to run docker commands without sudo
  user: name=vagrant append=yes groups=docker