- name: nginx install and conf
  hosts: all
  become: true
  vars:
    nginx_listen_port: 8080

  tasks:
  - name: update
    apt:
     update_cache=yes
    tags: 
    - update apt

  - name: nginx install
    apt:
     name: nginx
     state: latest
    tags: 
     - nginx-package
    
  - name: nginx conf
    template:
     src: ./nginx/nginx.conf.j2
     dest: /etc/nginx/nginx.conf
    notify:
    - reload nginx
    tags:
    - nginx-configuration

  handlers:
  - name: restart nginx
    systemd:
      name: nginx
      state: restarted
      enabled: yes

  - name: reload nginx
    systemd:
      name: nginx
      state: reloaded